server:
  port: '8085'
  error:
    include-message: always

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: 
    password:
    port: 2525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:maindb

  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: customMessage:br.com.zup.notafiscal.dto.NovaVendaRequest
